# Generated by Django 4.1.1 on 2022-10-01 11:30

from django.db import migrations, models
import leffavuokraamo.models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rental_duration',
        ),
        migrations.AddField(
            model_name='rental',
            name='return_date',
            field=models.DateField(default=leffavuokraamo.models.Rental.return_date_time),
        ),
    ]
