# Generated by Django 4.1.1 on 2022-10-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0003_alter_rental_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(to='leffavuokraamo.director'),
        ),
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(to='leffavuokraamo.tag'),
        ),
    ]
