# Generated by Django 4.1.1 on 2022-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0005_genre_film_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='is_loaned',
            field=models.BooleanField(default=False),
        ),
    ]
