# Generated by Django 4.1.1 on 2022-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0006_alter_film_is_loaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
