# Generated by Django 4.1.1 on 2022-10-05 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0007_rental_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='return_date',
            new_name='last_return_date',
        ),
        migrations.AddField(
            model_name='rental',
            name='date_returned',
            field=models.DateField(default=datetime.date(2022, 10, 5)),
            preserve_default=False,
        ),
    ]
