# Generated by Django 4.1 on 2022-10-07 10:36

from django.db import migrations, models
import leffavuokraamo.models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0009_alter_rental_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='is_loaned',
            field=models.BooleanField(default=False, verbose_name='On vuokrattuna'),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Puhuttu kieli'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(verbose_name='Julkaisupäivä'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Elokuvan nimi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='date_returned',
            field=models.DateField(null=True, verbose_name='Päivä jolloin palautettu'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='last_return_date',
            field=models.DateField(default=leffavuokraamo.models.Rental.return_date_time, verbose_name='Viimeinen palautuspäivä'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(auto_now_add=True, verbose_name='Päivä jolloin vuokrattu'),
        ),
    ]
