# Generated by Django 4.1.1 on 2022-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0010_film_leffavuokra_title_732ea7_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='leffavuokra_name_bff0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag'], name='leffavuokra_tag_87cdec_idx'),
        ),
    ]
