# Generated by Django 4.1.1 on 2022-10-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leffavuokraamo', '0010_alter_film_is_loaned_alter_film_language_and_more'),
        ('leffavuokraamo', '0011_genre_leffavuokra_name_bff0c6_idx_and_more'),
    ]

    operations = [
    ]
